### ISSUE TITLE
Support redux-form v6

### ISSUE THREAD

**Issue by leesiongchan** [Lighthouse-io/redux-form-schema#11]
`redux-form` v6 did not yet simplify the process of validation, and I found this library solves most of the use cases. Would that be possible to upgrade this library to support v6 as well?

**Comment by willmcclellan** [comment]
Sorry for late reply... We'll be updating our apps with v6 of redux-form in the coming weeks, so we will update then

**Comment by eminaz** [comment]
any updates?

**Comment by IdoBl** [comment]
Hi @willmcclellan,
Thanks for your excellent work.
Did you manage to update the module to support redux-form v6?

**Comment by willmcclellan** [comment]
It is on our roadmap to do this, we just haven't got round to it yet. Unfortunately I can't say when that will be, but happy to accept pull requests if anyone wants to move it along

**Comment by eduardoinnorway** [comment]
Anything happening?

**Comment by willmcclellan** [comment]
We're tracking this in #13, it's pretty close just need to verify documentation is updated then merge/publish. You can always install from that branch if you want to test in the meantime

**Comment by eduardoinnorway** [comment]
Because of deadlines, we just did our own version of redux-form + schema with:

[JSON schema](http://json-schema.org) 
and 
[AJV](https://github.com/epoberezkin/ajv)

We will for sure try it our version, we keep in touch.

**Comment by willmcclellan** [comment]
We'll no longer be maintaining this module, see the Readme for more info https://github.com/Lighthouse-io/redux-form-schema/blob/master/README.md

**Comment by eduardoinnorway** [comment]
Field error validation is not the same as validating against a schema. I can't see what would make this module obselete in Redux-Form v6? Yes you can define things at a Field level, but all the things defined should come to from a schema, the modules should just render and nothing else.

**Comment by willmcclellan** [comment]
@eduardoinnorway we agree, we're still using a schema to define our form validation - but we don't need this or any other module to manage it. 

Previously, Redux Form could only validate at the form level, which was difficult for us to manage, hence this module. Now we can do it at the field level we don't need to bundle the validation up into one function. 

Saying that, if you do want to handle your validation at the form level then this module would be useful. If that becomes a priority for us we might revive it but at this stage that's not the case. Happy for someone to take #13 forward if they like.
