### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by GautierT** [Lighthouse-io/redux-form-schema#12]
Hi @willmcclellan and @amanda-lighthouseio,

Is this repo still maintained ?

Thanks !

**Comment by willmcclellan** [comment]
@GautierT We're still using it in production, but not with v6 of Redux Form. We'll be migrating at some point in the near future but I can't any timelines.

**Comment by GautierT** [comment]
@willmcclellan Thanks for your answer. Keep us posted. It's an interesting project !

**Comment by clu3** [comment]
Any update @willmcclellan ? Are you using v6 yet?

**Comment by willmcclellan** [comment]
@clu3 Not yet I'm afraid, it's just not a priority for us ATM. Happy to accept PRs if interested

**Comment by jpmelnik** [comment]
It's an interesting project! I hope news soon. Thanks.

**Comment by willmcclellan** [comment]
We'll no longer be maintaining this module, see the Readme for more info https://github.com/Lighthouse-io/redux-form-schema/blob/master/README.md
